name: mvp-docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Dockerhub
      run: echo ${{ secrets.DOCKER_PASSWORD}} | docker login
        -u ${{secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker Image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/mvp .
    - name: Publish to Dockerhub
      run: docker push ${{ secrets.DOCKER_USERNAME}}/mvp